"use client";

import Link from "next/link";
import { upload } from "@vercel/blob/client";
import { useCallback, useEffect, useMemo, useRef, useState, useTransition } from "react";
import CardPreview from "../../../../components/physical-card/CardPreview";
import type { CardSideDesign } from "../../../../lib/physical-card/templates";
import { validatePrint } from "../../../../lib/physical-card/validation";
import { requestPrintOrderAction, savePhysicalDesignAction } from "../actions";

type Snapshot = { front: CardSideDesign; back: CardSideDesign };
type Initial = Snapshot & { id: string; name: string; version: number; publicUrl: string; updatedAt: string };
const clone = <T,>(value: T): T => JSON.parse(JSON.stringify(value)) as T;

export default function PhysicalCardEditor({ initial }: { initial: Initial }) {
  const [name, setName] = useState(initial.name); const [snapshot, setSnapshot] = useState<Snapshot>({ front: initial.front, back: initial.back });
  const [face, setFace] = useState<"front" | "back">("front"); const [guides, setGuides] = useState(true); const [presentation, setPresentation] = useState(false); const [view3d, setView3d] = useState(false);
  const [status, setStatus] = useState<"saved" | "pending" | "saving" | "error">("saved"); const [message, setMessage] = useState(""); const [version, setVersion] = useState(initial.version); const [savedAt, setSavedAt] = useState(initial.updatedAt);
  const [history, setHistory] = useState<Snapshot[]>([]); const [future, setFuture] = useState<Snapshot[]>([]); const [pending, startTransition] = useTransition(); const first = useRef(true);
  const side = snapshot[face]; const findings = useMemo(() => validatePrint(snapshot.front, snapshot.back), [snapshot]);
  const commit = useCallback((next: Snapshot) => { setHistory(h => [...h.slice(-29), clone(snapshot)]); setFuture([]); setSnapshot(next); setStatus("pending"); }, [snapshot]);
  const update = <K extends keyof CardSideDesign>(key: K, value: CardSideDesign[K]) => commit({ ...snapshot, [face]: { ...side, [key]: value } });
  const save = useCallback(async () => { setStatus("saving"); try { const result = await savePhysicalDesignAction({ id: initial.id, name, front: snapshot.front, back: snapshot.back, expectedVersion: version }); setVersion(result.version); setSavedAt(result.savedAt); setStatus("saved"); } catch (e) { setMessage(e instanceof Error ? e.message : "Error al guardar."); setStatus("error"); } }, [initial.id, name, snapshot, version]);
  useEffect(() => { if (first.current) { first.current = false; return; } if (status !== "pending") return; const timer = setTimeout(() => void save(), 1200); return () => clearTimeout(timer); }, [save, status]);
  const undo = () => { const previous = history.at(-1); if (!previous) return; setFuture(f => [clone(snapshot), ...f]); setHistory(h => h.slice(0, -1)); setSnapshot(previous); setStatus("pending"); };
  const redo = () => { const next = future[0]; if (!next) return; setHistory(h => [...h, clone(snapshot)]); setFuture(f => f.slice(1)); setSnapshot(next); setStatus("pending"); };
  const restore = () => commit({ front: clone(initial.front), back: clone(initial.back) });
  const fileUpload = async (file: File, field: "logoUrl" | "photoUrl") => { if (!file.type.match(/^image\/(png|jpeg|webp)$/) || file.size > 5_000_000) { setMessage("Usa PNG, JPG o WebP de hasta 5 MB."); return; } try { setMessage("Subiendo imagen…"); const blob = await upload(`physical-designs/${initial.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`, file, { access: "public", handleUploadUrl: "/api/blob/upload" }); update(field, blob.url); setMessage("Imagen cargada."); } catch { setMessage("No fue posible cargar la imagen."); } };
  const exportPng = async () => { const current = snapshot[face]; const canvas = document.createElement("canvas"); canvas.width = 1082; canvas.height = 720; const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.fillStyle = current.background; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = current.primary; if (current.layout.includes("side-stripe")) ctx.fillRect(0, 0, 120, 720); else ctx.fillRect(0, 650, 1082, 70); ctx.fillStyle = current.text; ctx.font = "bold 54px Arial"; ctx.fillText(current.name || current.company, 90, 270, 700); ctx.font = "28px Arial"; ctx.fillStyle = current.muted; ctx.fillText([current.position, current.company].filter(Boolean).join(" · "), 90, 320, 700); ctx.font = "24px Arial"; ctx.fillText(current.tagline, 90, 390, 700); const download = () => { const a = document.createElement("a"); a.download = `${name}-${face}-300dpi.png`; a.href = canvas.toDataURL("image/png"); a.click(); }; if (current.qrVisible) { const image = new Image(); image.crossOrigin = "anonymous"; image.onload = () => { ctx.fillStyle = "white"; ctx.fillRect(810, 420, 220, 220); ctx.drawImage(image, 825, 435, 190, 190); download(); }; image.onerror = download; image.src = `https://api.qrserver.com/v1/create-qr-code/?size=600x600&margin=16&data=${encodeURIComponent(initial.publicUrl)}`; } else download(); };
  const requestOrder = () => startTransition(async () => { try { const quantity = Number(prompt("Cantidad de tarjetas", "50")); if (!quantity) return; await requestPrintOrderAction({ designId: initial.id, quantity, productionMethod: "ADHESIVE_LABEL", printSides: "DOUBLE", finish: "MATTE", notes: "" }); setMessage("Pedido solicitado correctamente."); } catch (e) { setMessage(e instanceof Error ? e.message : "No fue posible solicitar el pedido."); } });
  return <div className="space-y-4">
    <header className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-800 bg-slate-900/80 p-3"><div className="flex min-w-0 items-center gap-3"><Link href="/dashboard/physical-designs" className="rounded-lg bg-slate-800 px-3 py-2 text-sm text-white">← Volver</Link><input aria-label="Nombre del diseño" value={name} onChange={e => { setName(e.target.value); setStatus("pending"); }} className="min-w-0 rounded-lg bg-transparent px-2 py-2 font-bold text-white outline-none focus:ring-2 focus:ring-blue-500"/></div><div className="flex flex-wrap items-center gap-2"><span className={`text-xs ${status === "error" ? "text-red-400" : "text-slate-400"}`}>{status === "saving" ? "Guardando…" : status === "pending" ? "Cambios pendientes" : status === "error" ? "Error al guardar" : `Guardado ${new Date(savedAt).toLocaleTimeString("es-CL")}`}</span><button onClick={undo} disabled={!history.length} className="rounded-lg bg-slate-800 px-3 py-2 text-xs text-white disabled:opacity-40">Deshacer</button><button onClick={redo} disabled={!future.length} className="rounded-lg bg-slate-800 px-3 py-2 text-xs text-white disabled:opacity-40">Rehacer</button><button onClick={() => void save()} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white">Guardar</button></div></header>
    {message && <div role="status" className="rounded-xl border border-blue-500/20 bg-blue-500/10 px-4 py-3 text-sm text-blue-200">{message}</div>}
    <div className="flex justify-end"><a href={`/api/physical-designs/${initial.id}/pdf`} className="rounded-xl bg-slate-800 px-4 py-2.5 text-xs font-bold text-white">Descargar PDF de impresión</a></div>
    <div className="grid gap-4 xl:grid-cols-[330px_1fr]">
      <aside className="max-h-[76vh] space-y-5 overflow-y-auto rounded-2xl border border-slate-800 bg-slate-900/60 p-4">
        <div className="grid grid-cols-2 gap-2"><button onClick={() => setFace("front")} className={`rounded-lg py-2 text-xs font-bold ${face === "front" ? "bg-blue-600 text-white" : "bg-slate-800 text-slate-300"}`}>Anverso</button><button onClick={() => setFace("back")} className={`rounded-lg py-2 text-xs font-bold ${face === "back" ? "bg-blue-600 text-white" : "bg-slate-800 text-slate-300"}`}>Reverso</button></div>
        <EditorSection title="Contenido">{([['name','Nombre'],['position','Cargo'],['company','Empresa'],['tagline','Frase principal'],['phone','Teléfono'],['email','Correo'],['website','Sitio web'],['instagram','Instagram'],['address','Dirección'],['nfcText','Mensaje NFC']] as const).map(([key, label]) => <label key={key} className="block text-xs text-slate-400">{label}<input value={side[key]} onChange={e => update(key, e.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white"/></label>)}</EditorSection>
        <EditorSection title="Identidad"><div className="grid grid-cols-2 gap-3">{([['background','Fondo'],['primary','Principal'],['secondary','Acento'],['text','Texto'],['muted','Secundario']] as const).map(([key,label]) => <label key={key} className="text-xs text-slate-400">{label}<span className="mt-1 flex rounded-lg border border-slate-700 bg-slate-950 p-1"><input type="color" value={side[key]} onChange={e => update(key, e.target.value)} className="h-8 w-full cursor-pointer bg-transparent"/></span></label>)}</div><label className="block text-xs text-slate-400">Logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e => e.target.files?.[0] && void fileUpload(e.target.files[0], "logoUrl")} className="mt-1 block w-full text-xs text-slate-400"/></label><label className="block text-xs text-slate-400">Fotografía<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e => e.target.files?.[0] && void fileUpload(e.target.files[0], "photoUrl")} className="mt-1 block w-full text-xs text-slate-400"/></label></EditorSection>
        <EditorSection title="Elementos y distribución"><Toggle label="Mostrar QR" checked={side.qrVisible} onChange={v => update("qrVisible", v)}/><Toggle label="Mostrar NFC" checked={side.nfcVisible} onChange={v => update("nfcVisible", v)}/><label className="block text-xs text-slate-400">Tamaño QR: {side.qrSizeMm} mm<input type="range" min="18" max="28" step="1" value={side.qrSizeMm} onChange={e => update("qrSizeMm", Number(e.target.value))} className="w-full"/></label><label className="block text-xs text-slate-400">Alineación<select value={side.alignment} onChange={e => update("alignment", e.target.value as CardSideDesign["alignment"])} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white"><option value="left">Izquierda</option><option value="center">Centro</option><option value="right">Derecha</option></select></label><button onClick={() => commit({ ...snapshot, back: { ...snapshot.back, background: snapshot.front.background, primary: snapshot.front.primary, secondary: snapshot.front.secondary, text: snapshot.front.text, muted: snapshot.front.muted } })} className="w-full rounded-lg bg-slate-800 px-3 py-2 text-xs text-white">Copiar colores al reverso</button><button onClick={restore} className="w-full rounded-lg px-3 py-2 text-xs text-amber-300 hover:bg-amber-500/10">Restaurar plantilla</button></EditorSection>
      </aside>
      <main className="rounded-2xl border border-slate-800 bg-slate-950/50 p-4 sm:p-7"><div className="mb-5 flex flex-wrap justify-center gap-2"><ToggleButton active={guides} onClick={() => setGuides(!guides)}>Guías</ToggleButton><ToggleButton active={presentation} onClick={() => setPresentation(!presentation)}>Presentación</ToggleButton><ToggleButton active={view3d} onClick={() => setView3d(!view3d)}>Vista 3D</ToggleButton></div><div className={view3d ? "[perspective:1000px]" : ""}><div className={view3d ? "transition-transform duration-700 [transform:rotateY(-18deg)_rotateX(5deg)] hover:[transform:rotateY(18deg)_rotateX(2deg)]" : ""}><CardPreview side={side} publicUrl={initial.publicUrl} guides={guides && !presentation} label={face === "front" ? "Anverso" : "Reverso"}/></div></div><p className="mt-5 text-center text-xs text-slate-500">CR80 · 85,60 × 53,98 mm · sangrado 3 mm · salida 300 DPI</p><div className="mt-5 flex flex-wrap justify-center gap-2"><button onClick={() => void exportPng()} disabled={findings.some(f => f.level === "ERROR")} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-40">Descargar PNG 300 DPI</button><a href={`/api/physical-designs/${initial.id}/svg?side=${face}`} className="rounded-xl bg-slate-800 px-4 py-2.5 text-xs font-bold text-white">Descargar SVG vectorial</a><button onClick={requestOrder} disabled={pending || findings.some(f => f.level === "ERROR")} className="rounded-xl bg-amber-500 px-4 py-2.5 text-xs font-bold text-slate-950 disabled:opacity-40">Solicitar impresión</button></div><div className="mx-auto mt-6 max-w-xl space-y-2"><h3 className="text-sm font-bold text-white">Revisión de impresión</h3>{findings.length === 0 ? <p className="rounded-lg bg-emerald-500/10 p-3 text-sm text-emerald-300">Diseño listo para exportar.</p> : findings.map((finding, i) => <p key={`${finding.message}-${i}`} className={`rounded-lg border p-3 text-xs ${finding.level === "ERROR" ? "border-red-500/20 bg-red-500/10 text-red-300" : finding.level === "WARNING" ? "border-amber-500/20 bg-amber-500/10 text-amber-200" : "border-blue-500/20 bg-blue-500/10 text-blue-200"}`}><b>{finding.level === "ERROR" ? "Error" : finding.level === "WARNING" ? "Advertencia" : "Recomendación"}:</b> {finding.message}</p>)}</div><details className="mx-auto mt-4 max-w-xl text-xs text-slate-400"><summary className="cursor-pointer">Comprobar contenido del QR</summary><a href={initial.publicUrl} target="_blank" rel="noreferrer" className="mt-2 block break-all text-blue-400">{initial.publicUrl}</a></details></main>
    </div>
  </div>;
}

function EditorSection({ title, children }: { title: string; children: React.ReactNode }) { return <details open className="space-y-3 rounded-xl border border-slate-800 bg-slate-950/40 p-3"><summary className="cursor-pointer text-sm font-bold text-white">{title}</summary><div className="space-y-3 pt-2">{children}</div></details>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center justify-between text-xs text-slate-300"><span>{label}</span><input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} className="h-4 w-4 accent-blue-600"/></label>; }
function ToggleButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button onClick={onClick} className={`rounded-lg px-3 py-2 text-xs font-bold ${active ? "bg-blue-600 text-white" : "bg-slate-800 text-slate-300"}`}>{children}</button>; }
