export type BlogPost = { slug:string; title:string; description:string; category:string; readTime:string; published:string; intro:string; sections:{heading:string; paragraphs:string[]}[] };

export const posts: BlogPost[] = [
  { slug:"que-es-una-tarjeta-nfc", title:"¿Qué es una tarjeta NFC y cómo funciona?", description:"Descubre qué es una tarjeta NFC, cómo comparte información y por qué reemplaza a la tarjeta de presentación de papel.", category:"Guía", readTime:"7 min", published:"2026-08-14", intro:"Una tarjeta NFC es una tarjeta física con un pequeño chip que permite abrir información digital al acercarla a un teléfono. En SmartNFC, esa información es un perfil profesional actualizable que ayuda a compartir datos y captar nuevos contactos.", sections:[
    {heading:"¿Qué significa NFC?",paragraphs:["NFC significa Near Field Communication o comunicación de campo cercano. Es una tecnología inalámbrica de muy corto alcance: el intercambio ocurre cuando dos dispositivos compatibles están a pocos centímetros.","La tarjeta no necesita batería. El teléfono genera el campo que activa el chip y abre una dirección web segura en el navegador."]},
    {heading:"¿Qué puede compartir una tarjeta NFC?",paragraphs:["Puede abrir un perfil con nombre, cargo, teléfono, correo, sitio web, redes sociales, catálogo, documentos y botones de contacto. A diferencia del papel, esa información se puede actualizar sin fabricar una tarjeta nueva.","SmartNFC también permite que la otra persona deje sus datos, transformando una presentación en un prospecto disponible para seguimiento."]},
    {heading:"¿Se necesita una aplicación?",paragraphs:["No. En teléfonos compatibles basta con acercar la tarjeta. Como respaldo, un código QR permite abrir el mismo perfil desde cualquier cámara móvil."]},
    {heading:"¿Para quién es útil?",paragraphs:["Es especialmente útil para vendedores, ejecutivos, profesionales independientes, inmobiliarias, equipos de eventos y empresas que necesitan una identidad consistente para muchos colaboradores."]},
  ]},
  { slug:"tarjeta-nfc-vs-codigo-qr", title:"Tarjeta NFC vs. código QR: ¿cuál conviene?", description:"Comparamos NFC y QR para compartir contactos y explicamos por qué la mejor experiencia combina ambas tecnologías.", category:"Comparativa", readTime:"5 min", published:"2026-08-14", intro:"NFC y QR cumplen una misión parecida: llevar a una persona desde el mundo físico a una experiencia digital. La diferencia está en cómo se activa esa experiencia y en qué contexto resulta más natural.", sections:[
    {heading:"La ventaja de NFC",paragraphs:["NFC ofrece una interacción rápida y memorable: basta con acercar el teléfono a la tarjeta. No hay que abrir la cámara ni encuadrar un código, lo que funciona muy bien en reuniones, ventas y eventos."]},
    {heading:"La ventaja del código QR",paragraphs:["El QR es universal, visible y fácil de incluir en señalética, vitrinas o impresos. También sirve como respaldo para teléfonos que no tienen NFC activado."]},
    {heading:"¿Por qué no elegir solo uno?",paragraphs:["La experiencia más robusta combina ambos. NFC entrega el gesto simple y diferencial; QR asegura cobertura y permite compartir el perfil desde más superficies.","SmartNFC usa NFC y QR para abrir el mismo perfil actualizable, evitando duplicar información o administrar enlaces diferentes."]},
  ]},
  { slug:"networking-empresarial", title:"Cómo medir el retorno del networking empresarial", description:"Aprende a convertir reuniones y eventos en oportunidades medibles con perfiles digitales, captura de contactos y seguimiento.", category:"Estrategia", readTime:"6 min", published:"2026-08-14", intro:"El networking suele medirse por percepciones: cuántas personas conocimos o cuántas tarjetas entregamos. Para conocer su retorno real, hay que conectar cada interacción con datos que permitan seguimiento.", sections:[
    {heading:"Define la acción que importa",paragraphs:["Antes de un evento, decide qué debe hacer el contacto: guardar datos, pedir una reunión, revisar una propuesta o dejar su información. Un perfil digital puede priorizar esa acción."]},
    {heading:"Registra interacciones y prospectos",paragraphs:["Una tarjeta de papel desaparece después de ser entregada. Una identidad digital permite medir aperturas y registrar prospectos que voluntariamente comparten sus datos."]},
    {heading:"Haz seguimiento mientras hay contexto",paragraphs:["La probabilidad de continuar una conversación aumenta cuando el seguimiento ocurre pronto. Centralizar los contactos captados ayuda a que el equipo actúe sin depender de notas o fotografías de tarjetas."]},
    {heading:"Métricas recomendadas",paragraphs:["Revisa perfiles activos, aperturas, contactos captados, tasa de conversión a reunión y oportunidades generadas por evento o colaborador. El objetivo no es acumular vistas, sino aprender qué encuentros generan resultados."]},
  ]},
];

export function getPost(slug:string){ return posts.find((post)=>post.slug===slug); }
