import Link from "next/link";
import { prisma } from "../../../lib/prisma";

export const dynamic = "force-dynamic";

interface PageProps { searchParams: Promise<{ q?: string; status?: string }> }

const planLabels: Record<string, string> = { LOCAL_IMPULSA: "Impulsa", LOCAL_FUNDADOR: "Cliente fundador", LOCAL_PERSONALIZADO: "Personalizado" };
const statusLabels: Record<string, string> = { PENDING: "Pendiente", ACTIVE: "Activo", SUSPENDED: "Suspendido", EXPIRED: "Vencido", CANCELLED: "Cancelado" };

export default async function LocalesPage({ searchParams }: PageProps) {
  const params = await searchParams;
  const q = params.q?.trim() || "";
  const status = params.status || "";
  const locales = await prisma.company.findMany({
    where: { name: q ? { contains: q, mode: "insensitive" } : undefined, productLicenses: { some: { product: "LOCAL", status: status ? status as "PENDING" | "ACTIVE" | "SUSPENDED" | "EXPIRED" | "CANCELLED" : undefined } } },
    orderBy: { createdAt: "desc" },
    include: { productLicenses: { where: { product: "LOCAL" }, take: 1 }, users: { where: { role: "COMPANY_OWNER" }, take: 1 }, _count: { select: { localCampaigns: true } } },
  });
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><span className="text-[10px] font-black uppercase tracking-[0.18em] text-amber-600 dark:text-amber-400">SmartNFC Local</span><h1 className="mt-1 text-2xl font-black tracking-tight text-slate-900 dark:text-white">Gestión de locales</h1><p className="mt-1.5 text-xs font-medium text-slate-500 dark:text-slate-400">Registra negocios locales, administra su licencia y revisa sus campañas activas.</p></div><Link href="/superadmin/locales/nuevo" className="inline-block rounded-xl bg-amber-500 px-4 py-2.5 text-center text-xs font-extrabold text-slate-950 shadow-md transition hover:bg-amber-400">＋ Registrar local</Link></div>
    <form method="GET" className="flex flex-col gap-3 rounded-2xl border border-slate-200/50 bg-white p-4 shadow-sm dark:border-white/5 dark:bg-slate-900/60 sm:flex-row"><input name="q" defaultValue={q} placeholder="Buscar local por nombre..." className="flex-1 rounded-xl border border-slate-200 bg-slate-50 px-4 py-2.5 text-xs outline-none focus:ring-1 focus:ring-amber-500 dark:border-slate-800 dark:bg-slate-950 dark:text-white"/><select name="status" defaultValue={status} className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-2.5 text-xs outline-none focus:ring-1 focus:ring-amber-500 dark:border-slate-800 dark:bg-slate-950 dark:text-slate-300"><option value="">Todos los estados</option><option value="ACTIVE">Activos</option><option value="PENDING">Pendientes</option><option value="SUSPENDED">Suspendidos</option><option value="EXPIRED">Vencidos</option><option value="CANCELLED">Cancelados</option></select><button className="rounded-xl bg-slate-900 px-5 py-2.5 text-xs font-bold text-white dark:bg-slate-800">Filtrar</button>{(q||status)&&<Link href="/superadmin/locales" className="flex items-center justify-center rounded-xl bg-slate-100 px-5 py-2.5 text-xs font-bold text-slate-700 dark:bg-slate-950 dark:text-slate-300">Limpiar</Link>}</form>
    <div className="overflow-hidden rounded-2xl border border-slate-200/50 bg-white shadow-sm dark:border-white/5 dark:bg-slate-900/60"><div className="overflow-x-auto"><table className="w-full border-collapse text-left text-xs"><thead><tr className="border-b border-slate-200 bg-slate-50 text-[9px] font-bold uppercase tracking-wider text-slate-400 dark:border-white/5 dark:bg-slate-900/50 dark:text-slate-500"><th className="px-5 py-3.5">Local</th><th className="px-5 py-3.5">Estado</th><th className="px-5 py-3.5">Plan</th><th className="px-5 py-3.5">Campañas</th><th className="px-5 py-3.5">Administrador</th><th className="px-5 py-3.5">Registro</th><th className="px-5 py-3.5 text-right">Acciones</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-white/5">{locales.length===0?<tr><td colSpan={7} className="px-5 py-10 text-center text-slate-400">No se encontraron locales. Registra el primero para comenzar.</td></tr>:locales.map(local=>{const license=local.productLicenses[0];const owner=local.users[0];return <tr key={local.id} className="text-slate-700 hover:bg-amber-50/40 dark:text-slate-300 dark:hover:bg-amber-500/5"><td className="px-5 py-3.5"><Link href={`/superadmin/empresas/${local.id}`} className="font-bold text-amber-700 hover:underline dark:text-amber-400">{local.name}</Link><span className="block font-mono text-[10px] text-slate-400">/{local.slug}</span></td><td className="px-5 py-3.5"><span className={`inline-flex rounded border px-2 py-0.5 text-[8px] font-extrabold uppercase ${license?.status==="ACTIVE"?"border-emerald-500/20 bg-emerald-500/10 text-emerald-600":"border-slate-300 bg-slate-100 text-slate-600 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300"}`}>{statusLabels[license?.status||""]||license?.status}</span></td><td className="px-5 py-3.5 font-semibold">{planLabels[license?.planCode||""]||license?.planCode}</td><td className="px-5 py-3.5"><b>{local._count.localCampaigns}</b> / {license?.includedCampaigns??0}</td><td className="px-5 py-3.5">{owner?<><span className="font-semibold">{owner.name}</span><span className="block text-[10px] text-slate-400">{owner.email}</span></>:<span className="italic text-slate-400">No asignado</span>}</td><td className="px-5 py-3.5 text-slate-400">{new Date(local.createdAt).toLocaleDateString("es-CL")}</td><td className="px-5 py-3.5 text-right"><Link href={`/superadmin/empresas/${local.id}`} className="inline-flex rounded-lg border border-slate-200 px-2.5 py-1.5 text-[10px] font-extrabold hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-900">Editar / Ver</Link></td></tr>})}</tbody></table></div></div>
  </div>;
}
