"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createCompanyAction, getActiveLocalFounderLicensesCountAction } from "../../actions";

export default function NuevoLocalPage() {
  const router = useRouter();
  const [name,setName]=useState(""); const [slug,setSlug]=useState(""); const [category,setCategory]=useState(""); const [address,setAddress]=useState(""); const [phone,setPhone]=useState(""); const [notes,setNotes]=useState("");
  const [plan,setPlan]=useState("LOCAL_IMPULSA"); const [status,setStatus]=useState("ACTIVE"); const [campaigns,setCampaigns]=useState(1); const [branches,setBranches]=useState(1); const [touchpoints,setTouchpoints]=useState(3); const [startsAt,setStartsAt]=useState(""); const [expiresAt,setExpiresAt]=useState("");
  const [createAdmin,setCreateAdmin]=useState(true); const [adminName,setAdminName]=useState(""); const [adminEmail,setAdminEmail]=useState(""); const [founderCount,setFounderCount]=useState(0); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); const [success,setSuccess]=useState(false); const [warning,setWarning]=useState<string|null>(null);
  useEffect(()=>{getActiveLocalFounderLicensesCountAction().then(setFounderCount).catch(()=>undefined)},[]);
  useEffect(()=>{if(plan==="LOCAL_IMPULSA"||plan==="LOCAL_FUNDADOR"){setCampaigns(1);setBranches(1);setTouchpoints(3)}else{setCampaigns(5);setBranches(5);setTouchpoints(15)}},[plan]);
  const updateName=(value:string)=>{setName(value);setSlug(value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""))};
  async function submit(event:React.FormEvent){event.preventDefault();setError(null);setWarning(null);if(!name.trim()||!slug){setError("El nombre y el identificador URL son obligatorios.");return}if(createAdmin&&(!adminName.trim()||!adminEmail.trim())){setError("Completa el nombre y correo del administrador.");return}setLoading(true);try{const details=[category&&`Categoría: ${category}`,address&&`Dirección: ${address}`,phone&&`Teléfono: ${phone}`,notes].filter(Boolean).join("\n");const result=await createCompanyAction({name,slug,internalNotes:details||undefined,adminName:createAdmin?adminName:undefined,adminEmail:createAdmin?adminEmail:undefined,localLicense:{planCode:plan as never,status:status as never,includedCampaigns:campaigns,includedBranches:branches,includedTouchpoints:touchpoints,startsAt:startsAt||undefined,expiresAt:expiresAt||undefined}});if(!result.success){setError(result.error||"No se pudo registrar el local.");return}setSuccess(true);setWarning(result.emailWarning||null);setTimeout(()=>router.push("/superadmin/locales"),result.emailWarning?2600:1300)}catch(err){setError(err instanceof Error?err.message:"Ocurrió un error inesperado.")}finally{setLoading(false)}}
  const field="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-2.5 text-xs outline-none focus:ring-1 focus:ring-amber-500 dark:border-slate-800 dark:bg-slate-950 dark:text-white disabled:opacity-50";
  const label="block text-[10px] font-bold uppercase tracking-wider text-slate-400";
  return <div className="mx-auto max-w-4xl space-y-6">
    <div><Link href="/superadmin/locales" className="mb-2 block text-xs font-extrabold uppercase tracking-wider text-amber-600 hover:underline dark:text-amber-400">← Volver a locales</Link><h1 className="text-2xl font-black tracking-tight text-slate-900 dark:text-white">Registrar nuevo local</h1><p className="mt-1 text-xs font-medium text-slate-500 dark:text-slate-400">Crea el negocio, activa SmartNFC Local y asigna su administrador principal.</p></div>
    {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-xs font-bold text-red-700 dark:border-red-900 dark:bg-red-950/40 dark:text-red-300">{error}</div>}{success&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-xs font-bold text-emerald-700">Local registrado correctamente. Redirigiendo…</div>}{warning&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs font-bold text-amber-800">{warning}</div>}
    <form onSubmit={submit} className="space-y-5">
      <section className="space-y-4 rounded-2xl border border-slate-200/60 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900/50"><div><h2 className="text-sm font-black text-slate-900 dark:text-white">Datos del local</h2><p className="mt-1 text-[11px] text-slate-400">Información administrativa para identificar el negocio.</p></div><div className="grid gap-4 md:grid-cols-2"><div><label className={label}>Nombre del local</label><input required value={name} onChange={e=>updateName(e.target.value)} placeholder="Ej. Café Costanera" className={field}/></div><div><label className={label}>Identificador URL</label><input required value={slug} onChange={e=>setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,""))} placeholder="cafe-costanera" className={`${field} font-mono`}/></div><div><label className={label}>Categoría</label><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Ej. Cafetería" className={field}/></div><div><label className={label}>Teléfono</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+56 9…" className={field}/></div><div className="md:col-span-2"><label className={label}>Dirección</label><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Dirección comercial del local" className={field}/></div><div className="md:col-span-2"><label className={label}>Notas internas</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3} placeholder="Información de contrato, implementación o facturación" className={field}/></div></div></section>
      <section className="space-y-4 rounded-2xl border border-amber-200 bg-white p-6 shadow-sm dark:border-amber-500/20 dark:bg-slate-900/50"><div><h2 className="text-sm font-black text-amber-700 dark:text-amber-400">Licencia SmartNFC Local</h2><p className="mt-1 text-[11px] text-slate-400">Capacidad de campañas, sucursales y puntos QR/NFC.</p></div><div className="grid gap-4 md:grid-cols-3"><div><label className={label}>Plan</label><select value={plan} onChange={e=>setPlan(e.target.value)} className={field}><option value="LOCAL_IMPULSA">Impulsa</option><option value="LOCAL_FUNDADOR">Cliente fundador ({founderCount}/5 activas)</option><option value="LOCAL_PERSONALIZADO">Personalizado</option></select></div><div><label className={label}>Estado</label><select value={status} onChange={e=>setStatus(e.target.value)} className={field}><option value="ACTIVE">Activo</option><option value="PENDING">Pendiente</option><option value="SUSPENDED">Suspendido</option><option value="EXPIRED">Vencido</option><option value="CANCELLED">Cancelado</option></select></div><div><label className={label}>Campañas</label><input type="number" min={1} value={campaigns} disabled={plan!=="LOCAL_PERSONALIZADO"} onChange={e=>setCampaigns(Number(e.target.value))} className={field}/></div><div><label className={label}>Sucursales</label><input type="number" min={1} value={branches} disabled={plan!=="LOCAL_PERSONALIZADO"} onChange={e=>setBranches(Number(e.target.value))} className={field}/></div><div><label className={label}>Puntos QR/NFC</label><input type="number" min={1} value={touchpoints} disabled={plan!=="LOCAL_PERSONALIZADO"} onChange={e=>setTouchpoints(Number(e.target.value))} className={field}/></div><div><label className={label}>Inicio</label><input type="date" value={startsAt} onChange={e=>setStartsAt(e.target.value)} className={field}/></div><div><label className={label}>Vencimiento</label><input type="date" value={expiresAt} onChange={e=>setExpiresAt(e.target.value)} className={field}/></div></div></section>
      <section className="space-y-4 rounded-2xl border border-slate-200/60 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900/50"><label className="flex cursor-pointer items-center gap-2 text-xs font-bold text-slate-800 dark:text-slate-200"><input type="checkbox" checked={createAdmin} onChange={e=>setCreateAdmin(e.target.checked)} className="h-4 w-4 rounded text-amber-500"/> Crear cuenta para el administrador del local</label>{createAdmin&&<div className="grid gap-4 md:grid-cols-2"><div><label className={label}>Nombre completo</label><input required value={adminName} onChange={e=>setAdminName(e.target.value)} className={field}/></div><div><label className={label}>Correo electrónico</label><input type="email" required value={adminEmail} onChange={e=>setAdminEmail(e.target.value)} className={field}/></div></div>}</section>
      <div className="flex justify-end gap-3"><Link href="/superadmin/locales" className="rounded-xl border border-slate-200 bg-slate-100 px-6 py-3 text-xs font-bold text-slate-700 dark:border-slate-800 dark:bg-slate-950 dark:text-slate-300">Cancelar</Link><button disabled={loading||success} className="rounded-xl bg-amber-500 px-6 py-3 text-xs font-extrabold text-slate-950 shadow-md hover:bg-amber-400 disabled:opacity-50">{loading?"Registrando…":"Registrar local"}</button></div>
    </form>
  </div>;
}
